//reducer
export const POST_FETCH_FAIL = "POST_FETCH_FAIL";
export const POST_FETCH_DATA = "POST_FETCH_DATA";
export const POST_ADD_NEW_POST = "POST_ADD_NEW_POST";
export const POST_SET_HOME_POST = "POST_SET_HOME_POST"
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const HOME_POST_FETCH_FAIL = "HOME_POST_FETCH_FAIL";
export const HOME_POST_FETCH_SUCCESS = "HOME_POST_FETCH_SUCCESS";

//post
export const POST_SAGA_GET_POSTS = "POST_SAGA_GET_POSTS";
export const POST_SAGA_CHANGE_LIKE = "POST_SAGA_CHANGE_LIKE";
export const POST_SAGA_ADD_COMMENTS = "POST_SAGA_ADD_COMMENTS";
export const POST_SAGA_GET_HOME_POSTS = "POST_SAGA_GET_HOME_POSTS";