export const CHAT_ADD_NEW_CHAT = "CHAT_ADD_NEW_CHAT";
export const CHAT_SET_MESSAGES = "CHAT_SET_MESSAGES";
export const CHAT_SET_CHATS = "CHAT_SET_CHATS";
export const CHAT_ADD_NEW_MESSAGE = "CHAT_ADD_NEW_MESSAGE";

//saga
export const CHAT_SAGA_GET_CHATS = "CHAT_SAGA_GET_CHATS";
export const CHAT_SAGA_GET_MESSAGES = "CHAT_SAGA_GET_MESSAGES";
export const CHAT_SAGA_SEND_MESSAGE = "CHAT_SAGA_SEND_MESSAGE";
export const CHAT_SAGA_CREATE_CONVERSATION = "CHAT_SAGA_CREATE_CONVERSATION";
export const CHAT_SAGA_GET_SOCKET_MESSAGE = "CHAT_SAGA_GET_SOCKET_MESSAGE";
