//user reducer
export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SET_PROFILE_IMAGE = "USER_SET_PROFILE_IMAGE";
export const USER_SET_EDIT_PROFILE = "USER_SET_EDIT_PROFILE";

//sagas 
export const USER_SAGA_FETCH = "USER_SAGA_FETCH";
export const USER_SAGA_VERIFY_TOKEN = "USER_SAGA_VERIFY_TOKEN";
export const LOGOUT_SAGA_REQUEST = "LOGOUT_SAGA_REQUEST";
export const USER_SAGA_EDIT_PROFILE = "USER_SAGA_EDIT_PROFILE";
