//user reducer
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_SET_EDIT_PROFILE = "USER_SET_EDIT_PROFILE";
export const USER_SET_PROFILE_IMAGE = "USER_SET_PROFILE_IMAGE";
export const USER_SET_SEARCH_LOADING = "USER_SET_SEARCH_LOADING";
export const USER_SET_SEARCH = "USER_SET_SEARCH";
export const USER_SET_PROFILE_DATA = "USER_SET_PROFILE_DATA";


//sagas 
export const USER_SAGA_FETCH = "USER_SAGA_FETCH";
export const USER_SAGA_VERIFY_TOKEN = "USER_SAGA_VERIFY_TOKEN";
export const USER_SAGA_EDIT_PROFILE = "USER_SAGA_EDIT_PROFILE";
export const USER_SAGA_LOGOUT_REQUEST = "USER_SAGA_LOGOUT_REQUEST";
export const USER_SAGA_GET_SEARCHS = "USER_SAGA_GET_SEARCHS";
export const USER_SAGA_GET_PROFILE_DATA = "USER_SAGA_GET_PROFILE_DATA";